name: "CI / Application JS Cloudflare Feature"

on:
  workflow_call:
    inputs:
      environment:
        description: 'Deployment Environment'
        type: string
        required: true
      ref:
        type: string
        default: master
        description: >
          Reference used for this repository, so we can re-use it when
          referencing local actions, and avoid having to checkout this
          repository separately.
    secrets:
      NIXPKGS_PRIVATE_PAT:
        required: true
      DEPLOY_SECRETS:
        required: true

env:
  NIX_CONFIG: access-tokens = github.com=${{ secrets.NIXPKGS_PRIVATE_PAT }}

jobs:
  # Lint the code
  feature-lint:
    name: "Feature / Lint"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MatrixAI/.github/.github/actions/matrixai-env-setup@master
      - name: Run linting
        env:
          NIX_CONFIG: access-tokens = github.com=${{ secrets.NIXPKGS_PRIVATE_PAT }}
        run: |
          nix develop .#ci --command bash -c $'
          npm run lint
          '

  # Build the public
  feature-build:
    name: "Feature / Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: MatrixAI/.github
          ref: ${{ inputs.ref }}
          path: tmp/.github
      - name: Parse Secrets
        uses: ./tmp/.github/.github/actions/secrets-parse
        with:
          secrets: ${{ secrets.DEPLOY_SECRETS }}
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MatrixAI/.github/.github/actions/matrixai-env-setup@master
      - name: Setup Deploy Secrets
        run: |
          echo "${{ inputs.DEPLOY_SECRETS }}" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Run build
        env:
          NIX_CONFIG: access-tokens = github.com=${{ secrets.NIXPKGS_PRIVATE_PAT }}
        run: |
          nix develop .#ci --command bash -c $'
          npm run build --verbose
          '
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./public

  # Deploy the public
  feature-deployment:
    name: "Feature / Deployment"
    runs-on: ubuntu-latest
    needs: feature-build
    concurrency:
      group: feature-deployment
      cancel-in-progress: false
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: MatrixAI/.github
          ref: ${{ inputs.ref }}
          path: tmp/.github
      - name: Parse Secrets
        uses: ./tmp/.github/.github/actions/secrets-parse
        with:
          secrets: ${{ secrets.DEPLOY_SECRETS }}
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: MatrixAI/.github/.github/actions/matrixai-env-setup@master
      - uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public
      - name: Setup Deploy Secrets
        run: |
          echo "${{ inputs.DEPLOY_SECRETS }}" | jq -r 'to_entries | .[] | "\(.key)=\(.value)"' >> $GITHUB_ENV
      - name: Run deployment
        env:
          NIX_CONFIG: access-tokens = github.com=${{ secrets.NIXPKGS_PRIVATE_PAT }}
          name: "feature/${{ github.ref_name }}"
          url: "https://${{ github.ref_name }}.dev.zeta.house"
        run: |
          echo 'Perform service deployment for feature'
          echo "$SECRET1"
          echo "$SECRET2"
          echo "$SECRET3"
          nix develop .#ci --command bash -c $'
          npm run deploy -- \
            --feature "$GITHUB_REF_NAME" \
            --env "$GITHUB_REF_NAME"
          '
